"""Remove name from user

Revision ID: 0810643b7dcd
Revises: d5a1c817c80b
Create Date: 2024-12-11 10:32:21.336561

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0810643b7dcd"
down_revision: Union[str, None] = "d5a1c817c80b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
