"""Change field to JSON

Revision ID: d5a1c817c80b
Revises: 7b5c564650fa
Create Date: 2024-12-10 15:40:34.060863

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5a1c817c80b"
down_revision: Union[str, None] = "7b5c564650fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE reservation ALTER COLUMN seats_reserved TYPE JSON USING seats_reserved::json"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE reservation ALTER COLUMN seats_reserved TYPE TEXT USING seats_reserved::text"
    )
    # ### end Alembic commands ###
